name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  cleanup-preview:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Delete preview deployment
        run: |
          SERVICE_NAME="ctgov-web-preview-pr-${{ github.event.pull_request.number }}"

          # Delete the Cloud Run service
          gcloud run services delete ${SERVICE_NAME} \
            --region="${{ env.REGION }}" \
            --quiet || true

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.issue.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '🧹 Preview deployment has been cleaned up.'
            });
